version: "3"
networks:
    spark:


volumes:
    mysql_data: {}

services:
    spark-database:
        image: isal20/spark-backend:db
        container_name: spark-database
        hostname: spark-database
        restart: always
        env_file:
            - ./spark-backend/.env
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - spark

    spark-backend:
        image: isal20/spark-backend:1.0.0
        restart: always
        env_file:
            - ./spark-backend/.env
        ports:
            - "${PORT:-1337}:1337"
        environment:
            - "MYSQL_HOST=${MYSQL_HOST:-spark-database}"
            - "MYSQL_USER=${MYSQL_USER:-spark}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE:-sparkdb}"
        networks:
            - spark
        depends_on:
            - spark-database

    spark-webclient:
        image: ranim04/spark-webclient:customer # image has not been created yet
        container_name: "spark-webclient"
        ports:
            - "1338:1338"
        networks:
            - spark
        links:
            - spark-backend

    #spark-program:
    #    image: ranim04/spark-program:main
    #    container_name: "spark-program"
    #    networks:
    #        - spark
    #    links:
    #        - spark-backend

    spark-simulation:
        image: ranim04/spark-program:simulation
        container_name: "spark-simulation"
        networks:
            - spark
        links:
            - spark-backend
