version: "3"
networks:
    spark:


volumes:
    mysql_data: {}

services:
    mysql:
        image: mysql:latest
        container_name: spark-mysql-database
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - ./spark-backend/.env
        volumes:
            - mysql_data:/var/lib/mysql
            - ./spark-backend/db:/docker-entrypoint-initdb.d
        networks:
            - spark
    spark-backend:
        image: isal20/spark-backend:1.0.0
        restart: always
        env_file:
            - ./spark-backend/.env
        ports:
            - "${PORT}:1337"
        volumes:
            - ./spark-backend:/app
        networks:
            - spark
