version: "3"
networks:
    spark:


volumes:
    mysql_data: {}

services:
    mysql:
        image: mysql:latest
        container_name: spark-mysql-database
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - ./spark-backend/.env
        volumes:
            - mysql_data:/var/lib/mysql
            - ./spark-backend/db:/docker-entrypoint-initdb.d
        networks:
            - spark

    spark-backend:
        image: isal20/spark-backend:1.0.0
        restart: always
        env_file:
            - ./spark-backend/.env
        ports:
            - "${PORT}:1337"
        networks:
            - spark


    spark-webclient:
        image: ranim04/spark-webclient:customer     # image has not been created yet
        container_name: "spark-webclient"
        ports:
            - "1338:1338"
        networks:
            - spark
        links:
            - spark-backend


    #spark-program:
    #    image: ranim04/spark-program:main
    #    container_name: "spark-program"
    #    networks:
    #        - spark
    #    links:
    #        - spark-backend

    spark-simulation:
        image: ranim04/spark-program:simulation
        container_name: "spark-simulation"
        networks:
            - spark
        links:
            - spark-backend