version: '3'

tasks:
  config:
    cmds:
      - echo "Checking the configuration..."
      - docker-compose -f docker-compose.yml config

  run:
    cmds:
      - echo "Starting the backend..."
      - docker-compose -f docker-compose.yml up -d

  stop:
    cmds:
      - echo "Stopping the backend..."
      - docker-compose -f docker-compose.yml down --remove-orphans

  stop-backend:
    cmds:
      - echo "Stopping the backend..."
      - docker-compose -f docker-compose.yml down
  restart:
    cmds:
      - echo "Restarting the backend..."
      - docker-compose -f docker-compose.yml restart  
      
  run-backend:
    cmds:
      - echo "Starting the backend..."
      - docker-compose -f docker-compose.yml up -d spark-backend --remove-orphans

  logs:
    cmds:
      - echo "Showing the logs..."
      - docker-compose -f docker-compose.yml logs -f 
  status:
    cmds:
      - echo "Showing the status..."
      - docker-compose -f docker-compose.yml ps


  