version: '3'
tasks:
  config:
    cmds:
      - echo "Checking the configuration..."
      - docker-compose -f docker-compose.yml config

  run:
    cmds:
      - echo "Starting the backend and clients..."
      - docker-compose -f docker-compose.yml up -d nginx spark-database spark-backend1 spark-backend2 spark-backend3 spark-backend4 spark-backend5 spark-backend6 spark-backend7 spark-backend8 spark-backend9 spark-backend10  spark-adminclient spark-webclient
  
  run-simulation:
    cmds:
      - echo "Starting the simulation..."
      - docker-compose -f docker-compose.yml up -d spark-simulation
  
  run-dev:
    cmds:
      - echo "Starting the backend..."
      - docker-compose -f docker-compose.dev.yml up -d

  stop:
    cmds:
      - echo "Stopping the backend..."
      - docker-compose -f docker-compose.yml down --remove-orphans

  restart:
    cmds:
      - echo "Restarting the backend..."
      - docker-compose -f docker-compose.yml restart  
      
  logs:
    cmds:
      - echo "Showing the logs..."
      - docker-compose -f docker-compose.yml logs -f 
  
  status:
    cmds:
      - echo "Showing the status..."
      - docker-compose -f docker-compose.yml ps


  